remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: JaneGwaww
description:
  It’s Your Life.
  Share it. Celebrate it. Build it.
  AND HAVE FUN!

show_downloads: false
google_analytics: UA-150406661-2
